server:
  port: ${SPRING_API_PORT:3003}
  address: 0.0.0.0

logging:
  level:
    root: INFO
    org:
      springframework: warn
      ch:
        qos:
          logback: OFF
      hibernate:
        SQL: warn
        orm:
          connections:
            pooling: error

spring:
  profiles:
    active: prd
  application:
    name: walletcore
  datasource:
    url: jdbc:postgresql://${DATABASE_IP:localhost}:${DATABASE_PORT:5432}/${DATABASE_SCHEMA:walletcoredb}
    username: ${DATABASE_USER:walletcoreuserdb}
    password: ${DATABASE_PASSWORD:walletcore123}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format:
          sql: true
  sql:
    init:
      platform: postgres
      mode: always
      continue-on-error: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/wallet-realm

management:
  httpexchanges:
    recording:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    use-global-registry: true
    enable:
      jvm: true
    distribution:
      slo:
        http: '5ms,10ms,25ms,50ms,100ms,200ms,300ms,400ms,500ms,1s,2s,5s,10s,15s,20s,25s,30s'
    tags:
      application: '@project.name@'
  prometheus:
    metrics:
      export:
        enabled: true

kafka:
  bootstrap:
    servers: ${KAFKA_URL:localhost}:${KAFKA_PORT:9092}
  topic: walletcore.events
  group:
    id:
      config: ${KAFKA_GROUP_ID_CONFIG:walletcore-group}
info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'
    title: Wallet
    url:
      dev: http://localhost:3003
      prd: http://localhost:3003
      git: https://github.com/danielso2007/fc-eda-java
    contact:
      name: Daniel Oliveira
      email: danielso2007@gmail.com

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
  auto-tag-classes: false